services:
  - type: web
    name: LaravelApp
    runtime: php
    plan: free
    region: oregon
    buildCommand: |
      echo "Ejecutando build..."
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      mkdir -p database
      touch database/database.sqlite
      php artisan migrate --force
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      chmod -R 775 storage bootstrap/cache
      chown -R www-data:www-data storage bootstrap/cache
    startCommand: "php artisan serve --host 0.0.0.0 --port $PORT"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: database/database.sqlite
      - key: PORT
        value: 10000
